version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: perf
      include: scope
  - package-ecosystem: npm
    directory: /renderer
    schedule:
      interval: weekly
    commit-message:
      prefix: perf
      include: scope
    groups:
      patch:
        update-types:
          - patch
  - package-ecosystem: bundler
    directory: /scraper
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: pref
