version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      codeql-action:
        patterns: github/codeql-action/*
  - package-ecosystem: npm
    directory: /renderer
    schedule:
      interval: weekly
    groups:
      patch:
        update-types:
          - patch
  - package-ecosystem: bundler
    directory: /scraper
    schedule:
      interval: weekly
