name: pull-request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./scraper
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up runtimes
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          working_directory: ./scraper
      - name: Set up Ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          bundler-cache: true
          working-directory: ./scraper
      - name: Set up Playwright
        run: npx playwright install chromium-headless-shell
      - name: Scrape
        run: ruby main.rb
        env:
          MK_USERNAME: ${{ secrets.MK_USERNAME }}
          MK_PASSWORD: ${{ secrets.MK_PASSWORD }}

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./renderer
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up runtimes
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          working_directory: ./renderer
      - name: Set up Pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          package_json_file: renderer/package.json
          cache_dependency_path: renderer/pnpm-lock.yaml
          run_install: true
          cache: true
      - name: Build package
        run: pnpm build
