name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./scraper
    steps:
      - uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./scraper
      - name: Setup Playwright
        run: npx playwright install chromium-headless-shell
      - name: Scrape
        env:
          MK_USERNAME: ${{ secrets.MK_USERNAME }}
          MK_PASSWORD: ${{ secrets.MK_PASSWORD }}
        run: ruby main.rb

      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data.json
          git commit -m "perf: refresh data.json [skip ci]" || exit 0
          git push
